--select 'drop table ' || table_name || ' cascade constraints;' from user_tables;

/******* Master Data  *********/
CREATE TABLE "COUNTRIES"
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "CODE" VARCHAR2(250 BYTE) NOT NULL, -- Mã quốc gia
  "NAME" VARCHAR2(250 BYTE) NOT NULL, -- Tên quốc gia
  "DESCRIPTION" VARCHAR2(4000 BYTE)
);

CREATE TABLE "REGIONS"
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "CODE" VARCHAR2(50 BYTE) NOT NULL UNIQUE, -- Mã địa bàn
  "PROVINCE_CODE" VARCHAR2(50 BYTE) REFERENCES "REGIONS"("CODE"), -- Mã tỉnh/thành phố
  "DISTRICT_CODE" VARCHAR2(50 BYTE) REFERENCES "REGIONS"("CODE"), -- Mã quận/huyện
  "NAME" VARCHAR2(250 BYTE) NOT NULL, -- Tên địa bàn
  "IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL -- Địa bàn còn hiệu lực hay không
);

@Region.sql;

ALTER TABLE REGIONS
ADD PROVINCE_ID NUMBER(10,0) REFERENCES REGIONS(ID);
ALTER TABLE REGIONS
ADD DISTRICT_ID NUMBER(10,0) REFERENCES REGIONS(ID);

UPDATE REGIONS R1
SET R1.PROVINCE_ID = (SELECT R2.ID FROM REGIONS R2 WHERE R2.CODE = R1.PROVINCE_CODE);
UPDATE REGIONS R1
SET R1.DISTRICT_ID = (SELECT R2.ID FROM REGIONS R2 WHERE R2.CODE = R1.DISTRICT_CODE);

COMMIT;

ALTER TABLE REGIONS
DROP COLUMN PROVINCE_CODE;
ALTER TABLE REGIONS
DROP COLUMN DISTRICT_CODE;

CREATE TABLE "ASSET_TYPES" -- Nhóm tài sản
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "SYNC_ID" VARCHAR2(250 BYTE) NULL, -- Mã đồng bộ từ phần mềm QLTSC
  "CODE" VARCHAR2(250 BYTE) NOT NULL, -- Mã nhóm tài sản
  "NAME" VARCHAR2(250 BYTE) NOT NULL, -- Tên nhóm tài sản
  "DESCRIPTION" VARCHAR2(4000 BYTE), -- Mô tả
  "PARENT_ID" NUMBER(10,0) REFERENCES "ASSET_TYPES"("ID"), -- ID nhóm tài sản chả
  "START_DATE" DATE NULL, -- Ngày có hiệu lực
  "END_DATE" DATE NULL, -- Ngày kết thúc hiệu lực
  "IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL -- Còn hoạt động
);

CREATE TABLE "INCREASEMENT_CAUSES" -- Lý do tăng
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "SYNC_ID" VARCHAR2(250 BYTE) NULL, -- Mã đồng bộ từ phần mềm QLTSC
  "CODE" VARCHAR2(250 BYTE) NOT NULL, -- Mã lý do tăng
  "NAME" VARCHAR2(250 BYTE) NOT NULL, -- Tên lý do tăng
  "ASSET_TYPE_ID" NUMBER(10,0) REFERENCES "ASSET_TYPES"("ID") NULL -- Nhóm tài sản được áp dụng
);

CREATE TABLE "DECREASEMENT_CAUSES" -- Lý do giảm
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "SYNC_ID" VARCHAR2(250 BYTE) NULL, -- Mã đồng bộ từ phần mềm QLTSC
  "CODE" VARCHAR2(250 BYTE) NOT NULL, -- Mã lý do giảm
  "NAME" VARCHAR2(250 BYTE) NOT NULL, -- Tên lý do giảm
  "ASSET_TYPE_ID" NUMBER(10,0) REFERENCES "ASSET_TYPES"("ID") NULL -- Nhóm tài sản được áp dụng
);

CREATE TABLE "ASSET_SOURCES" -- Nguồn gốc hình thành tài sản
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "SYNC_ID" VARCHAR2(250 BYTE) NULL, -- Mã đồng bộ từ phần mềm QLTSC
  "CODE" VARCHAR2(250 BYTE) NOT NULL, -- Mã nguồn gốc hình thành tài sản
  "NAME" VARCHAR2(250 BYTE) NOT NULL -- Tên nguồn gốc hình thành tài sản
);

CREATE TABLE "ASSET_USAGE_STATES" -- Hiện trạng sử dụng tài sản
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "SYNC_ID" VARCHAR2(250 BYTE) NULL, -- Mã đồng bộ từ phần mềm QLTSC
  "CODE" VARCHAR2(250 BYTE) NOT NULL, -- Mã hiện trạng sử dụng tài sản
  "NAME" VARCHAR2(250 BYTE) NOT NULL, -- Tên hiện trạng sử dụng tài sản
  "ASSET_TYPE_ID" NUMBER(10,0) REFERENCES "ASSET_TYPES"("ID") NULL -- Nhóm tài sản được áp dụng
);

CREATE TABLE "ASSET_USAGE_PURPOSES" -- Mục đích sử dụng tài sản
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "SYNC_ID" VARCHAR2(250 BYTE) NULL, -- Mã đồng bộ từ phần mềm QLTSC
  "CODE" VARCHAR2(250 BYTE) NOT NULL, -- Mã mục đích sử dụng tài sản
  "NAME" VARCHAR2(250 BYTE) NOT NULL, -- Tên mục đích sử dụng tài sản
  "ASSET_TYPE_ID" NUMBER(10,0) REFERENCES "ASSET_TYPES"("ID") NULL -- Nhóm tài sản được áp dụng
);

CREATE TABLE "ASSET_MUTATION_TYPES" -- Loại biến động
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "CODE" VARCHAR2(250 BYTE) NOT NULL, -- Mã loại biến động
  "NAME" VARCHAR2(250 BYTE) NOT NULL -- Tên loại biến động
);

CREATE TABLE "UNIT_LEVELS" -- Cấp đơn vị
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "CODE" VARCHAR2(250 BYTE) NOT NULL, -- Mã cấp đơn vị
  "NAME" VARCHAR2(250 BYTE) NOT NULL -- Tên cấp đơn vị
);

CREATE TABLE "UNIT_TYPES" -- Loại đơn vị
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "SYNC_ID" VARCHAR2(250 BYTE) NULL, -- Mã đồng bộ từ phần mềm QLTSC
  "CODE" VARCHAR2(250 BYTE) NOT NULL, -- Mã loại đơn vị
  "NAME" VARCHAR2(250 BYTE) NOT NULL -- Tên loại đơn vị
);

CREATE TABLE "UNITS" -- Đơn vị
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "SYNC_ID" VARCHAR2(250 BYTE) NULL, -- Mã đồng bộ từ phần mềm QLTSC (Mã T)
  "CODE" VARCHAR2(250 BYTE) NOT NULL UNIQUE, -- Mã đơn vị
  "NATIONAL_BUDGET_CODE" VARCHAR2(250 BYTE) UNIQUE, -- Mã đơn vị ngân sách
  "NAME" VARCHAR2(500 BYTE) NOT NULL, -- Tên đơn vị
  "UNIT_LEVEL_ID" NUMBER(10,0) REFERENCES "UNIT_LEVELS"("ID") NOT NULL, -- ID cấp đơn vị
  "UNIT_TYPE_ID" NUMBER(10,0) REFERENCES "UNIT_TYPES"("ID") NULL, -- ID loại đơn vị
  "PARENT_ID" NUMBER(10,0) REFERENCES "UNITS"("ID") NULL, -- ID đơn vị cha
  "REGION_ID" NUMBER(10,0) REFERENCES "REGIONS"("ID") NULL, -- Mã địa bàn
  "ADDRESS" VARCHAR2(4000 BYTE), -- Địa chỉ
  "PHONE_NUMBER" VARCHAR2(4000 BYTE), -- Điện thoại
  "FAX" VARCHAR2(4000 BYTE), -- Số fax
  "ACCOUNTING_STANDARD" NUMBER(10,0) -- chế độ hoạch toán
);

CREATE TABLE "UNIT_ASSET_TYPES" -- Bảng phân quyền đơn vị truy cập tài sản theo nhóm tài sản
(
  "UNIT_ID" NUMBER(10,0) REFERENCES "UNITS"("ID"), -- ID đơn vị
  "ASSET_TYPE_ID" NUMBER(10,0) REFERENCES "ASSET_TYPES"("ID"), -- ID nhóm tài sản
  PRIMARY KEY("UNIT_ID", "ASSET_TYPE_ID")
);

/******* System  *********/
CREATE TABLE "DATA_PROTECTION_KEYS" -- Keys mã hóa dữ liệu
(	
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY, 
  "FRIENDLY_NAME" VARCHAR2(4000 BYTE), -- Tên key
  "XML" VARCHAR2(4000 BYTE) -- Thông tin key
);

CREATE TABLE "SYSTEM_PARAMETERS" -- Tham số hệ thống
(
  "NAME" VARCHAR2(500 BYTE) PRIMARY KEY, -- Tên tham số
  "VALUE" VARCHAR2(4000 BYTE) NULL, -- Giá trị
  "DESCRIPTION" VARCHAR2(4000 BYTE) NULL, -- Mô tả
  "DATA_TYPE" NUMBER(10,0) NULL, -- Kiểu dữ liệu. 1: String. 2: Number. 3. Date
  "PARAMETER_TYPE" NUMBER(10,0) NOT NULL, -- Loại tham số. 1: Tham số hoạt động của hệ thống. 2: Tham số quy định phương thức quản lý tài sản. 3: Tham số báo cáo. 4: Tham số đồng bộ
  "ORDER" NUMBER(10,0) NULL -- Thứ tự sắp xếp
);

CREATE TABLE "IDENTITY_CLIENTS"  -- Cấu hình truy cập hệ thống
(	
  "IDENTITY_CLIENT_ID" VARCHAR2(900 BYTE) PRIMARY KEY, -- Mã ứng dụng truy cập
  "DESCRIPTION" VARCHAR2(100 BYTE) NOT NULL, -- Mô tả
  "SECRET_KEY" VARCHAR2(4000 BYTE) NOT NULL, -- Mã bí mật
  "CLIENT_TYPE" NUMBER(10,0) NOT NULL, -- Loại ứng dụng
  "IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL, -- Trạng thái hoạt động 
  "REFRESH_TOKEN_LIFE_TIME" NUMBER(10,0) NOT NULL, -- Thời gian tồn tại của Refresh Token
  "ALLOWED_ORIGIN" VARCHAR2(1000 BYTE)
);

CREATE TABLE "IDENTITY_REFRESH_TOKENS" -- Thông tin refresh token
(	
  "IDENTITY_REFRESH_TOKEN_ID" VARCHAR2(900 BYTE) PRIMARY KEY, -- ID refresh token
  "IDENTITY" VARCHAR2(50 BYTE) NOT NULL, -- Người dùng token
  "CLIENT_ID" VARCHAR2(4000 BYTE) NOT NULL, -- mã ứng dụng truy cập
  "ISSUED_UTC" TIMESTAMP (7) NOT NULL, -- Ngày cấp
  "EXPIRES_UTC" TIMESTAMP (7) NOT NULL, -- Ngày hết hạn
  "REFRESH_TOKEN" VARCHAR2(4000 BYTE) NOT NULL -- Mã refresh token
);

CREATE TABLE "PRIVILEGES" -- Quyền hạn sử dụng chức năng hệ thống
(
  "ID" VARCHAR2(50) PRIMARY KEY, -- Mã quyền hạn
  "NAME" VARCHAR2(250 BYTE) NOT NULL, -- Tên quyền hạn
  "DESCRIPTION" VARCHAR2(4000 BYTE), -- Mô tả
  "IS_EXPLOITING_PRIVILEGES" NUMBER(1,0) -- Đánh dấu quyền hạn tài khoản khai thác
);

CREATE TABLE "ROLES" -- Nhóm người dùng
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY, 
  "NAME" VARCHAR2(250 BYTE) NOT NULL, -- Tên người dùng
  "UNIT_ID" NUMBER(10,0) REFERENCES "UNITS"("ID"),
  "DESCRIPTION" VARCHAR2(4000 BYTE), -- Mô tả
  "IS_EXPLOITING_ROLE" NUMBER(1,0) -- Đánh dấu role khai thác
);

CREATE TABLE "USERS" -- Tài khoản người dùng hệ thống
(	
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY, 
  "USER_NAME" VARCHAR2(4000 BYTE), -- Tên đăng nhập
  "NORMALIZED_USER_NAME" VARCHAR2(4000 BYTE), -- Tên đăng nhập viết chữ thường
  "EMAIL" VARCHAR2(4000 BYTE), -- Email
  "NORMALIZED_EMAIL" VARCHAR2(4000 BYTE), -- Email viết chữ thường
  "EMAIL_CONFIRMED" NUMBER(1,0) NOT NULL, -- Xác nhận email
  "PASSWORD_HASH" VARCHAR2(4000 BYTE), -- Mật khẩu mã hóa
  "SECURITY_STAMP" VARCHAR2(4000 BYTE), -- Mã bảo mật thông tin tài khoản
  "CONCURRENCY_STAMP" VARCHAR2(4000 BYTE), -- Mã bảo mật nhiều người đồng thời sử dụng tài khoản
  "PHONE_NUMBER" VARCHAR2(4000 BYTE), -- Số điện thoại
  "PHONE_NUMBER_CONFIRMED" NUMBER(1,0) NOT NULL, -- Xác nhận SĐT
  "TWO_FACTOR_ENABLED" NUMBER(1,0) NOT NULL, -- Bảo mật 2 lớp
  "LOCKOUT_END" TIMESTAMP (3) WITH TIME ZONE, -- Thời gian hết hạn khóa tài khoản
  "LOCKOUT_ENABLED" NUMBER(1,0) NOT NULL, -- Khóa tài khoản
  "ACCESS_FAILED_COUNT" NUMBER(10,0) NOT NULL, -- Số lần đăng nhập thất bại
  "FULL_NAME" VARCHAR2(250 BYTE), -- Tên người dùng
  "IS_ADMINISTRATOR" NUMBER(1,0) NOT NULL, -- Tài khoản quản trị
  "UNIT_ID" NUMBER(10,0) REFERENCES "UNITS"("ID") NOT NULL, -- ID đơn vị tài khoản
  "SYNC_SOURCE" NUMBER(10,0) NULL, -- Đánh dấu dữ liệu được đồng bộ từ phần mềm khác
  "IS_EXPLOITING_USER" NUMBER(1,0), -- Đánh dấu tài khoản khai thác
  "DELETED_DATE" DATE NULL, -- Ngày xóa dữ liệu
  "DELETED_USER_ID" NUMBER(10,0) REFERENCES "USERS"("ID") NULL -- Người xóa dữ liệu
);

CREATE TABLE "ROLE_PRIVILEGES" -- Quyền hạn nhóm người dùng
(
  "ROLE_ID" NUMBER(10,0) REFERENCES "ROLES"("ID"), -- ID nhóm người dùng
  "PRIVILEGE_ID" VARCHAR2(50) REFERENCES "PRIVILEGES"("ID"), -- Mã quyền hạn
  PRIMARY KEY("ROLE_ID","PRIVILEGE_ID")
);

CREATE TABLE "USER_PRIVILEGES" -- Quyền hạn người dùng
(	
  "USER_ID" NUMBER(10,0) REFERENCES "USERS"("ID"), -- ID người dùng
	"PRIVILEGE_ID" VARCHAR2(50) REFERENCES "PRIVILEGES"("ID"), -- Mã quyền hạn
  PRIMARY KEY("USER_ID","PRIVILEGE_ID")
);

CREATE TABLE "USER_ROLES" -- Người dùng thuộc nhóm
(	
  "USER_ID" NUMBER(10,0) REFERENCES "USERS"("ID"), -- ID người dùng
	"ROLE_ID" NUMBER(10,0) REFERENCES "ROLES"("ID"), -- ID nhóm người dùng
  PRIMARY KEY("USER_ID","ROLE_ID")
);


/******** Sync services ***********/
CREATE TABLE "SYNC_PRIVILEGES" -- Quyền hạn sử dụng chức năng đồng bộ
(
  "ID" VARCHAR2(50) PRIMARY KEY, -- Mã quyền hạn
  "NAME" VARCHAR2(250 BYTE) NOT NULL, -- Tên quyền hạn
  "DESCRIPTION" VARCHAR2(4000 BYTE) -- Mô tả
);

CREATE TABLE "SYNC_ROLES" -- Nhóm người dùng đồng bộ
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY, 
  "NAME" VARCHAR2(250 BYTE) NOT NULL, -- Tên người dùng
  "UNIT_ID" NUMBER(10,0) REFERENCES "UNITS"("ID"),
  "DESCRIPTION" VARCHAR2(4000 BYTE) -- Mô tả
);

CREATE TABLE "SYNC_USERS" -- Tài khoản đồng bộ
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY, 
  "USER_NAME" VARCHAR2(4000 BYTE), -- Tên tài khoản
  "PASSWORD_HASH" VARCHAR2(4000 BYTE), -- Mật khẩu mã hóa
  "UNIT_ID" NUMBER(10,0) REFERENCES "UNITS"("ID") NOT NULL, -- ID đơn vị sở hữu tài khoản
  "IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL -- Trạng thái hoạt động
);

CREATE TABLE "SYNC_ROLE_PRIVILEGES" -- Quyền hạn nhóm người dùng đồng bộ
(
  "SYNC_ROLE_ID" NUMBER(10,0) REFERENCES "SYNC_ROLES"("ID"), -- ID nhóm người dùng
  "SYNC_PRIVILEGE_ID" VARCHAR2(50) REFERENCES "SYNC_PRIVILEGES"("ID"), -- Mã quyền hạn
  PRIMARY KEY("SYNC_ROLE_ID","SYNC_PRIVILEGE_ID")
);

CREATE TABLE "SYNC_USER_PRIVILEGES" -- Quyền hạn người dùng đồng bộ
(	
  "SYNC_USER_ID" NUMBER(10,0) REFERENCES "SYNC_USERS"("ID"), -- ID người dùng
	"SYNC_PRIVILEGE_ID" VARCHAR2(50) REFERENCES "SYNC_PRIVILEGES"("ID"), -- Mã quyền hạn
  PRIMARY KEY("SYNC_USER_ID","SYNC_PRIVILEGE_ID")
);

CREATE TABLE "SYNC_USER_ROLES" -- Người dùng thuộc nhóm đồng bộ
(	
  "SYNC_USER_ID" NUMBER(10,0) REFERENCES "SYNC_USERS"("ID"), -- ID người dùng
	"SYNC_ROLE_ID" NUMBER(10,0) REFERENCES "SYNC_ROLES"("ID"), -- ID nhóm người dùng
  PRIMARY KEY("SYNC_USER_ID","SYNC_ROLE_ID")
);


/******* Business  *********/
CREATE TABLE "ASSETS" -- Tài sản
(
  "ID" NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY, -- Mã tự tăng
  "SYNC_SOURCE_ID" VARCHAR2(250 BYTE) NOT NULL, -- Mã tài sản đồng bộ từ phần mềm khác
  "CODE" VARCHAR2(250 BYTE) NOT NULL UNIQUE, -- Mã tài sản toàn quốc do kho cấp (tự động sinh)
  "SYNC_USER_ID" NUMBER(10,0) REFERENCES "SYNC_USERS"("ID") NOT NULL, -- Tài khoản đồng bộ
  "SYNC_DATE" DATE DEFAULT SYSDATE NOT NULL, -- Ngày đồng bộ
  "LAST_UPDATED_DATE" DATE DEFAULT SYSDATE NOT NULL,
  
  "DELETED_DATE" DATE NULL, -- Ngày xóa dữ liệu
  "DELETED_USER_ID" NUMBER(10,0) REFERENCES "USERS"("ID") NULL, -- Người xóa dữ liệu
  
  -- Thông tin biến động
  "IS_DECREASED" NUMBER(1,0), -- Đã giảm
  "DECREASEMENT_DATE" DATE, -- Ngày giảm
  "DECREASEMENT_CAUSE_ID" NUMBER(10,0) NULL REFERENCES "DECREASEMENT_CAUSES"("ID"), -- Lý do giảm
  "TRANSFER_UNIT_NAME" VARCHAR2(500 BYTE), -- Tên đơn vị ngoài ngành điều chuyển
  "INCREASEMENT_CAUSE_ID" NUMBER(10,0) NULL REFERENCES "INCREASEMENT_CAUSES"("ID"), -- Lý do tăng
  
  
  /*********** Thông tin tài sản **************/
  
  -- Thông tin chung
  "NAME" VARCHAR2(4000 BYTE) NOT NULL, -- Ten tài sản
  "DESCRIPTION" VARCHAR2(4000 BYTE) NULL, -- Mô tả tài sản
  "ASSET_TYPE_ID" NUMBER(10,0) REFERENCES "ASSET_TYPES"("ID") NOT NULL, -- Nhóm tài sản
  "ASSET_CATEGORY_ID" NUMBER(10,0) REFERENCES "ASSET_TYPES"("ID") NOT NULL, -- Nhóm tài sản lớn (cấp 2 trong cây nhóm tài sản)
  
  "UNIT_ID" NUMBER(10,0) REFERENCES "UNITS"("ID") NOT NULL, -- ID đơn vị quản lý tài sản
  "UNIT_NAME" VARCHAR2(4000 BYTE) NULL, -- Đơn vị sử dụng
  --"UNIT_DEPARTMENT_ID" NUMBER(10,0) REFERENCES "UNIT_DEPARTMENTS"("ID") NULL, -- ID bộ phận sử dụng tài sản (đối với đơn vị hành chính)
  "DEPARTMENT_CODE" VARCHAR2(250 BYTE) NULL, -- Mã bộ phận sử dụng tài sản (đối với đơn vị hành chính)
  "DEPARTMENT_NAME" VARCHAR2(500 BYTE) NULL, -- Tên bộ phận sử dụng tài sản (đối với đơn vị hành chính)
  "USER_NAME" VARCHAR2(500 BYTE) NULL, -- Cán bộ sử dụng
  
  -- PROJECT INFO
  --"UNIT_PROJECT_ID" NUMBER(10,0) REFERENCES "UNIT_PROJECTS"("ID") NULL, -- ID dự án (đối với đơn vị sự nghiệp)
  "PROJECT_CODE" VARCHAR2(250 BYTE), -- Mã dự án
  "PROJECT_NAME" VARCHAR2(1000 BYTE), -- Tên dự án
  "PROJECT_DESCRIPTION" VARCHAR2(4000 BYTE), -- Mô tả dự án
  "PROJECT_DECISION_NUMBER" VARCHAR2(250 BYTE), -- Số quyết định
  "PROJECT_EXPENSE" NUMBER(18,0), -- Tổng kinh phí
  "PROJECT_EXPENSE_STATE_BUDGET" NUMBER(18,0), -- Nguồn NSNN
  "PROJECT_EXPENSE_ODA" NUMBER(18,0), -- Nguồn ODA
  "PROJECT_EXPENSE_AID" NUMBER(18,0), -- Nguồn viện trợ
  "PROJECT_EXPENSE_OTHER" NUMBER(18,0), -- Nguồn khác
  "PROJECT_START_DATE" DATE, -- Ngày bắt đầu
  "PROJECT_END_DATE" DATE, -- Ngày kết thúc
  "PROJECT_INVESTOR" VARCHAR2(4000 BYTE) NULL,
  "PROJECT_LOCATION" VARCHAR2(4000 BYTE) NULL,
  "ASSET_SOURCE_ID" NUMBER(10,0) REFERENCES "ASSET_SOURCES"("ID"), -- Mã nguồn gốc tài sản
  "ACCOUNTING_STANDARD" NUMBER(10,0), -- Chế độ hạch toán. 1: Tài sản chỉ tính hao mòn. 2: Tài sản chỉ tính khấu hao. 3: Tài sản tính cả khấu hao/hao mòn
  "DEPRECIATION_RATE" NUMBER(10,3), -- Tỷ lệ khấu hao
  "AMORTIZATION_RATE" NUMBER(10,3), -- Tỷ lệ hao mòn
  "PROCUREMENT_PLAN" VARCHAR2(4000 BYTE), -- Kế hoạch mua sắm
  "PROCUREMENT_FORM" VARCHAR2(500 BYTE), -- Hình thức mua sắm
  
  -- Dates
  "INPUT_DATE" DATE, -- Ngày nhập thông tin
  "DATE_OF_USE" DATE, -- Ngày sử dụng
  "APPROVED_DATE" DATE, -- Ngày duyệt
  "EXPIRY_DATE" DATE, -- Ngày hết hạn sử dụng
  "MANUFACTURER_DATE" DATE, -- Ngày sản xuất
  "WARRANTY_EXPIRY_DATE" DATE, -- Ngày hết hạn bảo hành
  
  "USAGE_STATUS" VARCHAR2(500 BYTE), -- Tình trạng sử dụng
  "USAGE_STATE_ID" NUMBER(10,0) REFERENCES "ASSET_USAGE_STATES"("ID"), -- Hiện trạng sử dụng
  "USAGE_PURPOSE_ID" NUMBER(10,0) REFERENCES "ASSET_USAGE_PURPOSES"("ID"), -- Mục đích sử dụng
  "USAGE_FORM" VARCHAR2(500 BYTE), -- Hình thức sử dụng
  
  "APPROVER_NAME" VARCHAR2(500 BYTE), -- Người duyệt
  
  -- Giá trị
  "ORIGINAL_VALUE" NUMBER(18,0), -- Nguyên giá
  "ORIGINAL_VALUE_SOURCE_STATE_BUDGET" NUMBER(18,0), -- Nguồn NSNN
  "ORIGINAL_VALUE_SOURCE_ODA" NUMBER(18,0), -- Nguồn ODA
  "ORIGINAL_VALUE_SOURCE_AID" NUMBER(18,0), -- Nguồn viện trợ
  "ORIGINAL_VALUE_SOURCE_BORROW" NUMBER(18,0), -- Nguồn vay
  "ORIGINAL_VALUE_SOURCE_OTHER" NUMBER(18,0), -- Nguồn khác
  "RESIDUAL_VALUE" NUMBER(18,0), -- Giá trị còn lại
  "DISCOUNT_COMMISSION_VALUE" NUMBER(18,0), -- Hoa hồng/chiết khấu
  "DISCOUNT_COMMISSION_TO_BUDGET" NUMBER(18,0), -- Hoa hồng/chiết khấu nộp ngân sách nhà nước
  "DISCOUNT_COMMISSION_REMAIN" NUMBER(18,0), -- Hoa hồng/chiết khấu được giữ lại đơn vị

  -- Giấy tờ
  "DOCUMENT_ACCEPTANCE" VARCHAR2(250 BYTE), -- Biên bản nghiệm thu
  "DOCUMENT_DATE_ACCEPTANCE" VARCHAR2(250 BYTE), -- Ngày nghiệm thu
  "DOCUMENT_DELIVERY" VARCHAR2(250 BYTE), -- Biên bản bàn giao
  "DOCUMENT_DATE_DELIVERY" VARCHAR2(250 BYTE), -- Ngày bàn giao
  
  "DOCUMENT_RECEIPT" VARCHAR2(250 BYTE), -- Hóa đơn/chứng từ
  "DOCUMENT_DATE_RECEIPT" DATE, -- Ngày ký hóa đơn/chứng từ
  "DOCUMENT_OTHER" VARCHAR2(4000 BYTE), -- Chứng từ pháp lý khác

  /* Thông tin của từng nhóm tài sản, được phân biệt bởi tiền tố (sử dụng 2 cấp tài sản)
  - OA: Organization Asset: Tài sản tại cơ quan, tổ chức, đơn vị
  - NPA: National Public Asset: Tài sản được xác lập sở hữu toàn dân
  - INF: Infrastructure Asset : Tài sản kết cấu hạ tầng
  - LA: Land Asset : Đất đai
  - RES: Resource Asset: Tài nguyên
  - OPA: Organization Public Asset : Tài sản công tại doanh nghiệp*/
  
  
  /********* OA: Organization Asset: Tài sản tại cơ quan, tổ chức, đơn vị *********/
  "OA_LAND_AREA" NUMBER(20,3), -- Diện tích
  "OA_LAND_AREA_HEADQUARTER_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm trụ sở làm việc
  "OA_LAND_AREA_BUSINESS_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cơ sở hoạt động sự nghiệp
  "OA_LAND_AREA_HOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà để ở
  "OA_LAND_AREA_LEASE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cho thuê
  "OA_LAND_AREA_VACANT_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bỏ trống
  "OA_LAND_AREA_OCCUPIED_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bị lấn chiếm
  "OA_LAND_AREA_OTHER_USAGE" NUMBER(20,3), -- Hiện trạng:Diện tích sử dụng khác
  "OA_LAND_REGION_ID" NUMBER(10,0) REFERENCES "REGIONS"("ID"), -- Địa bàn
  "OA_LAND_ADDRESS" VARCHAR2(1000 BYTE), -- Địa chỉ
  "OA_LAND_USE_RIGHT_VALUE" NUMBER(18,0), -- Giá trị quyền sử dụng đấtInfo
  "OA_LAND_LOCAL_USE_RIGHT_VALUE" NUMBER(18,0), -- Giá trị quyền sử dụng đất theo khung giá đất địa phương
  "OA_LAND_DOCUMENT_LAND_USE_RIGHT" VARCHAR2(250 BYTE), -- Số giấy chứng nhận quyền sử dụng đất
  "OA_LAND_DOCUMENT_DATE_LAND_USE_RIGHT_DATE" DATE, -- Ngày chứng nhận quyền sử dụng đất
  "OA_LAND_DOCUMENT_LAND_ALLOCATE" VARCHAR2(250 BYTE), -- Số quyết định giao đất
  "OA_LAND_DOCUMENT_DATE_LAND_ALLOCATE" DATE, -- Ngày quyết định giao đất
  "OA_LAND_DOCUMENT_LAND_USE_RIGHT_TRANSFER" VARCHAR2(250 BYTE), -- Hợp đồng chuyển nhượng quyền sử dụng đất
  "OA_LAND_DOCUMENT_DATE_LAND_USE_RIGHT_TRANSFER" DATE, -- Ngày ký hợp đồng chuyển nhượng quyền sử dụng đất
  "OA_LAND_DOCUMENT_LAND_LEASE" VARCHAR2(250 BYTE), -- Số quyết định cho thuê đất
  "OA_LAND_DOCUMENT_DATE_LAND_LEASE" DATE, -- Ngày quyết định cho thuê đất
  "OA_LAND_DOCUMENT_LAND_USE_RIGHT_EVALUATION" VARCHAR2(250 BYTE), -- Biên bản xác định giá trị quyền sử dụng đất
  "OA_LAND_DOCUMENT_DATE_LAND_USE_RIGHT_EVALUATION" DATE, -- Ngày ký biên bản xác định giá trị quyền sử dụng đất

  "OA_HOUSE_LAND_ID" NUMBER(18,0) REFERENCES "ASSETS"("ID"), -- Mã tài sản đất
  "OA_HOUSE_NUMBER_OF_FLOOR" NUMBER(10,0), -- Số tầng (nhà)
  "OA_HOUSE_AREA_BUILDING" NUMBER(20,3), -- Diện tích xây dựng
  "OA_HOUSE_AREA_FLOOR" NUMBER(20,3), -- Diện tích sàn
  "OA_HOUSE_AREA_HEADQUARTER_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm trụ sở làm việc
  "OA_HOUSE_AREA_BUSINESS_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cơ sở hoạt động sự nghiệp
  "OA_HOUSE_AREA_HOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà để ở
  "OA_HOUSE_AREA_WAREHOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà kho
  "OA_HOUSE_AREA_TEMPORARY_HOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà tạm
  "OA_HOUSE_AREA_LEASE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cho thuê
  "OA_HOUSE_AREA_VACANT_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bỏ trống
  "OA_HOUSE_AREA_OCCUPIED_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bị lấn chiếm
  "OA_HOUSE_AREA_OTHER_USAGE" NUMBER(20,3), -- Hiện trạng:Diện tích sử dụng khác

  "OA_VEHICLE_COUNTRY_OF_ORIGIN" VARCHAR2(500 BYTE), -- Nước sản xuất
  "OA_VEHICLE_BRAND_NAME" VARCHAR2(500 BYTE), -- Nhãn hiệu
  "OA_VEHICLE_VEHICLE_IDENTIFICATION_NUMBER" VARCHAR2(250 BYTE), -- Số khung/Mã nhận dạng phương tiện
  "OA_VEHICLE_REGISTRATION_PLATE_NUMBER" VARCHAR2(250 BYTE), -- Biển kiểm soát/số hiệu kiểm soát
  "OA_VEHICLE_SIZE" NUMBER(10,0), -- Kích cỡ (Số chỗ ngồi/kích cỡ tàu ...)
  "OA_VEHICLE_CAPACITY" VARCHAR2(500 BYTE), -- Sức chứa (tải trọng/công suất ...)
  
  "OA_ABOVE_500M_ASSET_SPECIFICATIONS" VARCHAR2(4000 BYTE), -- Thông số kỹ thuật
  "OA_ABOVE_500M_ASSET_SERIAL_NUMBER" VARCHAR2(250 BYTE), -- Số serie
  "OA_ABOVE_500M_ASSET_SUPPLIER" VARCHAR2(500 BYTE), -- Nhà cung cấp
  "OA_ABOVE_500M_ASSET_COUNTRY_OF_ORIGIN" VARCHAR2(500 BYTE), -- Nước sản xuất
  "OA_ABOVE_500M_ASSET_BRAND_NAME" VARCHAR2(500 BYTE), -- Nhãn hiệu
  
  "OA_BELOW_500M_ASSET_SPECIFICATIONS" VARCHAR2(4000 BYTE), -- Thông số kỹ thuật
  "OA_BELOW_500M_ASSET_SERIAL_NUMBER" VARCHAR2(250 BYTE), -- Số serie
  "OA_BELOW_500M_ASSET_SUPPLIER" VARCHAR2(500 BYTE), -- Nhà cung cấp
  "OA_BELOW_500M_ASSET_COUNTRY_OF_ORIGIN" VARCHAR2(500 BYTE), -- Nước sản xuất
  "OA_BELOW_500M_ASSET_BRAND_NAME" VARCHAR2(500 BYTE), -- Nhãn hiệu


  /********* NPA: National Public Asset: Tài sản được xác lập sở hữu toàn dân **********/
  "NPA_LAND_AREA" NUMBER(20,3), -- Diện tích
  "NPA_LAND_AREA_HEADQUARTER_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm trụ sở làm việc
  "NPA_LAND_AREA_BUSINESS_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cơ sở hoạt động sự nghiệp
  "NPA_LAND_AREA_HOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà để ở
  "NPA_LAND_AREA_LEASE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cho thuê
  "NPA_LAND_AREA_VACANT_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bỏ trống
  "NPA_LAND_AREA_OCCUPIED_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bị lấn chiếm
  "NPA_LAND_AREA_OTHER_USAGE" NUMBER(20,3), -- Hiện trạng:Diện tích sử dụng khác
  "NPA_LAND_REGION_ID" NUMBER(10,0) REFERENCES "REGIONS"("ID"), -- Địa bàn
  "NPA_LAND_ADDRESS" VARCHAR2(1000 BYTE), -- Địa chỉ
  "NPA_LAND_USE_RIGHT_VALUE" NUMBER(18,0), -- Giá trị quyền sử dụng đấtInfo
  "NPA_LAND_LOCAL_USE_RIGHT_VALUE" NUMBER(18,0), -- Giá trị quyền sử dụng đất theo khung giá đất địa phương
  "NPA_LAND_DOCUMENT_LAND_USE_RIGHT" VARCHAR2(250 BYTE), -- Số giấy chứng nhận quyền sử dụng đất
  "NPA_LAND_DOCUMENT_DATE_LAND_USE_RIGHT_DATE" DATE, -- Ngày chứng nhận quyền sử dụng đất
  "NPA_LAND_DOCUMENT_LAND_ALLOCATE" VARCHAR2(250 BYTE), -- Số quyết định giao đất
  "NPA_LAND_DOCUMENT_DATE_LAND_ALLOCATE" DATE, -- Ngày quyết định giao đất
  "NPA_LAND_DOCUMENT_LAND_USE_RIGHT_TRANSFER" VARCHAR2(250 BYTE), -- Hợp đồng chuyển nhượng quyền sử dụng đất
  "NPA_LAND_DOCUMENT_DATE_LAND_USE_RIGHT_TRANSFER" DATE, -- Ngày ký hợp đồng chuyển nhượng quyền sử dụng đất
  "NPA_LAND_DOCUMENT_LAND_LEASE" VARCHAR2(250 BYTE), -- Số quyết định cho thuê đất
  "NPA_LAND_DOCUMENT_DATE_LAND_LEASE" DATE, -- Ngày quyết định cho thuê đất
  "NPA_LAND_DOCUMENT_LAND_USE_RIGHT_EVALUATION" VARCHAR2(250 BYTE), -- Biên bản xác định giá trị quyền sử dụng đất
  "NPA_LAND_DOCUMENT_DATE_LAND_USE_RIGHT_EVALUATION" DATE, -- Ngày ký biên bản xác định giá trị quyền sử dụng đất

  "NPA_HOUSE_LAND_ID" NUMBER(18,0) REFERENCES "ASSETS"("ID"), -- Mã tài sản đất
  "NPA_HOUSE_NUMBER_OF_FLOOR" NUMBER(10,0), -- Số tầng (nhà)
  "NPA_HOUSE_AREA_BUILDING" NUMBER(20,3), -- Diện tích xây dựng
  "NPA_HOUSE_AREA_FLOOR" NUMBER(20,3), -- Diện tích sàn
  "NPA_HOUSE_AREA_HEADQUARTER_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm trụ sở làm việc
  "NPA_HOUSE_AREA_BUSINESS_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cơ sở hoạt động sự nghiệp
  "NPA_HOUSE_AREA_HOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà để ở
  "NPA_HOUSE_AREA_WAREHOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà kho
  "NPA_HOUSE_AREA_TEMPORARY_HOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà tạm
  "NPA_HOUSE_AREA_LEASE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cho thuê
  "NPA_HOUSE_AREA_VACANT_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bỏ trống
  "NPA_HOUSE_AREA_OCCUPIED_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bị lấn chiếm
  "NPA_HOUSE_AREA_OTHER_USAGE" NUMBER(20,3), -- Hiện trạng:Diện tích sử dụng khác

  "NPA_VEHICLE_COUNTRY_OF_ORIGIN" VARCHAR2(500 BYTE), -- Nước sản xuất
  "NPA_VEHICLE_BRAND_NAME" VARCHAR2(500 BYTE), -- Nhãn hiệu
  "NPA_VEHICLE_VEHICLE_IDENTIFICATION_NUMBER" VARCHAR2(250 BYTE), -- Số khung/Mã nhận dạng phương tiện
  "NPA_VEHICLE_REGISTRATION_PLATE_NUMBER" VARCHAR2(250 BYTE), -- Biển kiểm soát/số hiệu kiểm soát
  "NPA_VEHICLE_SIZE" NUMBER(10,0), -- Kích cỡ (Số chỗ ngồi/kích cỡ tàu ...)
  "NPA_VEHICLE_CAPACITY" VARCHAR2(500 BYTE), -- Sức chứa (tải trọng/công suất ...)
  
  "NPA_OTHER_ASSET_SPECIFICATIONS" VARCHAR2(4000 BYTE), -- Thông số kỹ thuật
  "NPA_OTHER_ASSET_SERIAL_NUMBER" VARCHAR2(250 BYTE), -- Số serie
  "NPA_OTHER_ASSET_SUPPLIER" VARCHAR2(500 BYTE), -- Nhà cung cấp
  "NPA_OTHER_ASSET_COUNTRY_OF_ORIGIN" VARCHAR2(500 BYTE), -- Nước sản xuất
  "NPA_OTHER_ASSET_BRAND_NAME" VARCHAR2(500 BYTE), -- Nhãn hiệu
  
  
  "OTHER_INFORMATION" CLOB, -- Các thông tin khác
  "NOTES" CLOB -- Ghi chú
);

CREATE TABLE "ASSET_MUTATIONS" -- Biến động tài sản
(
  "ID" NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "ASSET_ID" NUMBER(18,0) REFERENCES "ASSETS"("ID") NOT NULL, -- ID tài sản
  "ASSET_CODE" VARCHAR2(250 BYTE) NOT NULL, -- Mã tài sản
  "ASSET_MUTATION_TYPE_ID" NUMBER(10,0) REFERENCES "ASSET_MUTATION_TYPES"("ID") NOT NULL,
  "SYNC_USER_ID" NUMBER(10,0) REFERENCES "SYNC_USERS"("ID") NOT NULL, -- Tài khoản đồng bộ
  "SYNC_DATE" DATE DEFAULT SYSDATE NOT NULL, -- Ngày đồng bộ
  
  "DELETED_DATE" DATE NULL, -- Ngày xóa dữ liệu
  "DELETED_USER_ID" NUMBER(10,0) REFERENCES "USERS"("ID") NULL, -- Người xóa dữ liệu
  
  -- Thông tin biến động
  "INCREASEMENT_CAUSE_ID" NUMBER(10,0) NULL REFERENCES "INCREASEMENT_CAUSES"("ID"), -- Lý do tăng
  "DECREASEMENT_CAUSE_ID" NUMBER(10,0) NULL REFERENCES "DECREASEMENT_CAUSES"("ID"), -- Lý do giảm
  "CHANGE_REASON" VARCHAR2(4000 BYTE), -- Lý do thay đổi
  "TRANSFER_UNIT_ID" NUMBER(10,0) REFERENCES "UNITS"("ID"), -- ID đơn vị điều chuyển
  "TRANSFER_UNIT_CODE" VARCHAR2(250 BYTE) REFERENCES "UNITS"("CODE"), -- Mã đơn vị điều chuyển
  "TRANSFER_UNIT_NAME" VARCHAR2(500 BYTE), -- Tên đơn vị ngoài ngành điều chuyển
  "DECREASEMENT_DATE" DATE, -- Ngày giảm

  /************* Thông tin tài sản, copy từ bảng tài sản *************/
  
  -- Thông tin chung
  "SYNC_SOURCE_ID" VARCHAR2(250 BYTE) NOT NULL, -- Mã tài sản cũ
  "NAME" VARCHAR2(4000 BYTE) NOT NULL, -- Ten tài sản
  "DESCRIPTION" VARCHAR2(4000 BYTE) NULL, -- Mô tả tài sản
  "ASSET_TYPE_ID" NUMBER(10,0) REFERENCES "ASSET_TYPES"("ID") NOT NULL, -- Nhóm tài sản
  "ASSET_CATEGORY_ID" NUMBER(10,0) REFERENCES "ASSET_TYPES"("ID") NOT NULL, -- Nhóm tài sản lớn (cấp 2 trong cây nhóm tài sản)
  
  "UNIT_ID" NUMBER(10,0) REFERENCES "UNITS"("ID") NOT NULL, -- ID đơn vị quản lý tài sản
  "UNIT_NAME" VARCHAR2(4000 BYTE) NULL, -- Đơn vị sử dụng
  --"UNIT_DEPARTMENT_ID" NUMBER(10,0) REFERENCES "UNIT_DEPARTMENTS"("ID") NULL, -- ID bộ phận sử dụng tài sản (đối với đơn vị hành chính)
  "DEPARTMENT_CODE" VARCHAR2(250 BYTE) NULL, -- Mã bộ phận sử dụng tài sản (đối với đơn vị hành chính)
  "DEPARTMENT_NAME" VARCHAR2(500 BYTE) NULL, -- Tên bộ phận sử dụng tài sản (đối với đơn vị hành chính)
  "USER_NAME" VARCHAR2(500 BYTE) NULL, -- Cán bộ sử dụng
  
  -- PROJECT INFO
  --"UNIT_PROJECT_ID" NUMBER(10,0) REFERENCES "UNIT_PROJECTS"("ID") NULL, -- ID dự án (đối với đơn vị sự nghiệp)
  "PROJECT_CODE" VARCHAR2(250 BYTE), -- Mã dự án
  "PROJECT_NAME" VARCHAR2(1000 BYTE), -- Tên dự án
  "PROJECT_DESCRIPTION" VARCHAR2(4000 BYTE), -- Mô tả dự án
  "PROJECT_DECISION_NUMBER" VARCHAR2(250 BYTE), -- Số quyết định
  "PROJECT_EXPENSE" NUMBER(18,0), -- Tổng kinh phí
  "PROJECT_EXPENSE_STATE_BUDGET" NUMBER(18,0), -- Nguồn NSNN
  "PROJECT_EXPENSE_ODA" NUMBER(18,0), -- Nguồn ODA
  "PROJECT_EXPENSE_AID" NUMBER(18,0), -- Nguồn viện trợ
  "PROJECT_EXPENSE_OTHER" NUMBER(18,0), -- Nguồn khác
  "PROJECT_START_DATE" DATE, -- Ngày bắt đầu
  "PROJECT_END_DATE" DATE, -- Ngày kết thúc
  "PROJECT_INVESTOR" VARCHAR2(4000 BYTE) NULL,
  "PROJECT_LOCATION" VARCHAR2(4000 BYTE) NULL,
  "ASSET_SOURCE_ID" NUMBER(10,0) REFERENCES "ASSET_SOURCES"("ID"), -- Mã nguồn gốc tài sản
  "ACCOUNTING_STANDARD" NUMBER(10,0), -- Chế độ hạch toán. 1: Tài sản chỉ tính hao mòn. 2: Tài sản chỉ tính khấu hao. 3: Tài sản tính cả khấu hao/hao mòn
  "DEPRECIATION_RATE" NUMBER(10,3), -- Tỷ lệ khấu hao
  "AMORTIZATION_RATE" NUMBER(10,3), -- Tỷ lệ hao mòn
  "PROCUREMENT_PLAN" VARCHAR2(4000 BYTE), -- Kế hoạch mua sắm
  "PROCUREMENT_FORM" VARCHAR2(500 BYTE), -- Hình thức mua sắm
  
  -- Dates
  "INPUT_DATE" DATE, -- Ngày nhập thông tin
  "DATE_OF_USE" DATE, -- Ngày sử dụng
  "APPROVED_DATE" DATE, -- Ngày duyệt
  "EXPIRY_DATE" DATE, -- Ngày hết hạn sử dụng
  "MANUFACTURER_DATE" DATE, -- Ngày sản xuất
  "WARRANTY_EXPIRY_DATE" DATE, -- Ngày hết hạn bảo hành
  
  "USAGE_STATUS" VARCHAR2(500 BYTE), -- Tình trạng sử dụng
  "USAGE_STATE_ID" NUMBER(10,0) REFERENCES "ASSET_USAGE_STATES"("ID"), -- Hiện trạng sử dụng
  "USAGE_PURPOSE_ID" NUMBER(10,0) REFERENCES "ASSET_USAGE_PURPOSES"("ID"), -- Mục đích sử dụng
  "USAGE_FORM" VARCHAR2(500 BYTE), -- Hình thức sử dụng
  
  "APPROVER_NAME" VARCHAR2(500 BYTE), -- Người duyệt
  
  -- Giá trị
  "ORIGINAL_VALUE" NUMBER(18,0), -- Nguyên giá
  "ORIGINAL_VALUE_SOURCE_STATE_BUDGET" NUMBER(18,0), -- Nguồn NSNN
  "ORIGINAL_VALUE_SOURCE_ODA" NUMBER(18,0), -- Nguồn ODA
  "ORIGINAL_VALUE_SOURCE_AID" NUMBER(18,0), -- Nguồn viện trợ
  "ORIGINAL_VALUE_SOURCE_BORROW" NUMBER(18,0), -- Nguồn vay
  "ORIGINAL_VALUE_SOURCE_OTHER" NUMBER(18,0), -- Nguồn khác
  "RESIDUAL_VALUE" NUMBER(18,0), -- Giá trị còn lại
  "DISCOUNT_COMMISSION_VALUE" NUMBER(18,0), -- Hoa hồng/chiết khấu
  "DISCOUNT_COMMISSION_TO_BUDGET" NUMBER(18,0), -- Hoa hồng/chiết khấu nộp ngân sách nhà nước
  "DISCOUNT_COMMISSION_REMAIN" NUMBER(18,0), -- Hoa hồng/chiết khấu được giữ lại đơn vị

  -- Giấy tờ
  "DOCUMENT_ACCEPTANCE" VARCHAR2(250 BYTE), -- Biên bản nghiệm thu
  "DOCUMENT_DATE_ACCEPTANCE" VARCHAR2(250 BYTE), -- Ngày nghiệm thu
  "DOCUMENT_DELIVERY" VARCHAR2(250 BYTE), -- Biên bản bàn giao
  "DOCUMENT_DATE_DELIVERY" VARCHAR2(250 BYTE), -- Ngày bàn giao
  
  "DOCUMENT_RECEIPT" VARCHAR2(250 BYTE), -- Hóa đơn/chứng từ
  "DOCUMENT_DATE_RECEIPT" DATE, -- Ngày ký hóa đơn/chứng từ
  "DOCUMENT_OTHER" VARCHAR2(4000 BYTE), -- Chứng từ pháp lý khác

  /* Thông tin của từng nhóm tài sản, được phân biệt bởi tiền tố (sử dụng 2 cấp tài sản)
  - OA: Organization Asset: Tài sản tại cơ quan, tổ chức, đơn vị
  - NPA: National Public Asset: Tài sản được xác lập sở hữu toàn dân
  - INF: Infrastructure Asset : Tài sản kết cấu hạ tầng
  - LA: Land Asset : Đất đai
  - RES: Resource Asset: Tài nguyên
  - OPA: Organization Public Asset : Tài sản công tại doanh nghiệp*/
  
  
  /********* OA: Organization Asset: Tài sản tại cơ quan, tổ chức, đơn vị *********/
  "OA_LAND_AREA" NUMBER(20,3), -- Diện tích
  "OA_LAND_AREA_HEADQUARTER_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm trụ sở làm việc
  "OA_LAND_AREA_BUSINESS_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cơ sở hoạt động sự nghiệp
  "OA_LAND_AREA_HOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà để ở
  "OA_LAND_AREA_LEASE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cho thuê
  "OA_LAND_AREA_VACANT_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bỏ trống
  "OA_LAND_AREA_OCCUPIED_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bị lấn chiếm
  "OA_LAND_AREA_OTHER_USAGE" NUMBER(20,3), -- Hiện trạng:Diện tích sử dụng khác
  "OA_LAND_REGION_ID" NUMBER(10,0) REFERENCES "REGIONS"("ID"), -- Địa bàn
  "OA_LAND_ADDRESS" VARCHAR2(1000 BYTE), -- Địa chỉ
  "OA_LAND_USE_RIGHT_VALUE" NUMBER(18,0), -- Giá trị quyền sử dụng đấtInfo
  "OA_LAND_LOCAL_USE_RIGHT_VALUE" NUMBER(18,0), -- Giá trị quyền sử dụng đất theo khung giá đất địa phương
  "OA_LAND_DOCUMENT_LAND_USE_RIGHT" VARCHAR2(250 BYTE), -- Số giấy chứng nhận quyền sử dụng đất
  "OA_LAND_DOCUMENT_DATE_LAND_USE_RIGHT_DATE" DATE, -- Ngày chứng nhận quyền sử dụng đất
  "OA_LAND_DOCUMENT_LAND_ALLOCATE" VARCHAR2(250 BYTE), -- Số quyết định giao đất
  "OA_LAND_DOCUMENT_DATE_LAND_ALLOCATE" DATE, -- Ngày quyết định giao đất
  "OA_LAND_DOCUMENT_LAND_USE_RIGHT_TRANSFER" VARCHAR2(250 BYTE), -- Hợp đồng chuyển nhượng quyền sử dụng đất
  "OA_LAND_DOCUMENT_DATE_LAND_USE_RIGHT_TRANSFER" DATE, -- Ngày ký hợp đồng chuyển nhượng quyền sử dụng đất
  "OA_LAND_DOCUMENT_LAND_LEASE" VARCHAR2(250 BYTE), -- Số quyết định cho thuê đất
  "OA_LAND_DOCUMENT_DATE_LAND_LEASE" DATE, -- Ngày quyết định cho thuê đất
  "OA_LAND_DOCUMENT_LAND_USE_RIGHT_EVALUATION" VARCHAR2(250 BYTE), -- Biên bản xác định giá trị quyền sử dụng đất
  "OA_LAND_DOCUMENT_DATE_LAND_USE_RIGHT_EVALUATION" DATE, -- Ngày ký biên bản xác định giá trị quyền sử dụng đất

  "OA_HOUSE_LAND_ID" NUMBER(18,0) REFERENCES "ASSETS"("ID"), -- Mã tài sản đất
  "OA_HOUSE_NUMBER_OF_FLOOR" NUMBER(10,0), -- Số tầng (nhà)
  "OA_HOUSE_AREA_BUILDING" NUMBER(20,3), -- Diện tích xây dựng
  "OA_HOUSE_AREA_FLOOR" NUMBER(20,3), -- Diện tích sàn
  "OA_HOUSE_AREA_HEADQUARTER_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm trụ sở làm việc
  "OA_HOUSE_AREA_BUSINESS_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cơ sở hoạt động sự nghiệp
  "OA_HOUSE_AREA_HOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà để ở
  "OA_HOUSE_AREA_WAREHOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà kho
  "OA_HOUSE_AREA_TEMPORARY_HOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà tạm
  "OA_HOUSE_AREA_LEASE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cho thuê
  "OA_HOUSE_AREA_VACANT_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bỏ trống
  "OA_HOUSE_AREA_OCCUPIED_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bị lấn chiếm
  "OA_HOUSE_AREA_OTHER_USAGE" NUMBER(20,3), -- Hiện trạng:Diện tích sử dụng khác

  "OA_VEHICLE_COUNTRY_OF_ORIGIN" VARCHAR2(500 BYTE), -- Nước sản xuất
  "OA_VEHICLE_BRAND_NAME" VARCHAR2(500 BYTE), -- Nhãn hiệu
  "OA_VEHICLE_VEHICLE_IDENTIFICATION_NUMBER" VARCHAR2(250 BYTE), -- Số khung/Mã nhận dạng phương tiện
  "OA_VEHICLE_REGISTRATION_PLATE_NUMBER" VARCHAR2(250 BYTE), -- Biển kiểm soát/số hiệu kiểm soát
  "OA_VEHICLE_SIZE" NUMBER(10,0), -- Kích cỡ (Số chỗ ngồi/kích cỡ tàu ...)
  "OA_VEHICLE_CAPACITY" VARCHAR2(500 BYTE), -- Sức chứa (tải trọng/công suất ...)
  
  "OA_ABOVE_500M_ASSET_SPECIFICATIONS" VARCHAR2(4000 BYTE), -- Thông số kỹ thuật
  "OA_ABOVE_500M_ASSET_SERIAL_NUMBER" VARCHAR2(250 BYTE), -- Số serie
  "OA_ABOVE_500M_ASSET_SUPPLIER" VARCHAR2(500 BYTE), -- Nhà cung cấp
  "OA_ABOVE_500M_ASSET_COUNTRY_OF_ORIGIN" VARCHAR2(500 BYTE), -- Nước sản xuất
  "OA_ABOVE_500M_ASSET_BRAND_NAME" VARCHAR2(500 BYTE), -- Nhãn hiệu
  
  "OA_BELOW_500M_ASSET_SPECIFICATIONS" VARCHAR2(4000 BYTE), -- Thông số kỹ thuật
  "OA_BELOW_500M_ASSET_SERIAL_NUMBER" VARCHAR2(250 BYTE), -- Số serie
  "OA_BELOW_500M_ASSET_SUPPLIER" VARCHAR2(500 BYTE), -- Nhà cung cấp
  "OA_BELOW_500M_ASSET_COUNTRY_OF_ORIGIN" VARCHAR2(500 BYTE), -- Nước sản xuất
  "OA_BELOW_500M_ASSET_BRAND_NAME" VARCHAR2(500 BYTE), -- Nhãn hiệu


  /********* NPA: National Public Asset: Tài sản được xác lập sở hữu toàn dân **********/
  "NPA_LAND_AREA" NUMBER(20,3), -- Diện tích
  "NPA_LAND_AREA_HEADQUARTER_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm trụ sở làm việc
  "NPA_LAND_AREA_BUSINESS_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cơ sở hoạt động sự nghiệp
  "NPA_LAND_AREA_HOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà để ở
  "NPA_LAND_AREA_LEASE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cho thuê
  "NPA_LAND_AREA_VACANT_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bỏ trống
  "NPA_LAND_AREA_OCCUPIED_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bị lấn chiếm
  "NPA_LAND_AREA_OTHER_USAGE" NUMBER(20,3), -- Hiện trạng:Diện tích sử dụng khác
  "NPA_LAND_REGION_ID" NUMBER(10,0) REFERENCES "REGIONS"("ID"), -- Địa bàn
  "NPA_LAND_ADDRESS" VARCHAR2(1000 BYTE), -- Địa chỉ
  "NPA_LAND_USE_RIGHT_VALUE" NUMBER(18,0), -- Giá trị quyền sử dụng đấtInfo
  "NPA_LAND_LOCAL_USE_RIGHT_VALUE" NUMBER(18,0), -- Giá trị quyền sử dụng đất theo khung giá đất địa phương
  "NPA_LAND_DOCUMENT_LAND_USE_RIGHT" VARCHAR2(250 BYTE), -- Số giấy chứng nhận quyền sử dụng đất
  "NPA_LAND_DOCUMENT_DATE_LAND_USE_RIGHT_DATE" DATE, -- Ngày chứng nhận quyền sử dụng đất
  "NPA_LAND_DOCUMENT_LAND_ALLOCATE" VARCHAR2(250 BYTE), -- Số quyết định giao đất
  "NPA_LAND_DOCUMENT_DATE_LAND_ALLOCATE" DATE, -- Ngày quyết định giao đất
  "NPA_LAND_DOCUMENT_LAND_USE_RIGHT_TRANSFER" VARCHAR2(250 BYTE), -- Hợp đồng chuyển nhượng quyền sử dụng đất
  "NPA_LAND_DOCUMENT_DATE_LAND_USE_RIGHT_TRANSFER" DATE, -- Ngày ký hợp đồng chuyển nhượng quyền sử dụng đất
  "NPA_LAND_DOCUMENT_LAND_LEASE" VARCHAR2(250 BYTE), -- Số quyết định cho thuê đất
  "NPA_LAND_DOCUMENT_DATE_LAND_LEASE" DATE, -- Ngày quyết định cho thuê đất
  "NPA_LAND_DOCUMENT_LAND_USE_RIGHT_EVALUATION" VARCHAR2(250 BYTE), -- Biên bản xác định giá trị quyền sử dụng đất
  "NPA_LAND_DOCUMENT_DATE_LAND_USE_RIGHT_EVALUATION" DATE, -- Ngày ký biên bản xác định giá trị quyền sử dụng đất

  "NPA_HOUSE_LAND_ID" NUMBER(18,0) REFERENCES "ASSETS"("ID"), -- Mã tài sản đất
  "NPA_HOUSE_NUMBER_OF_FLOOR" NUMBER(10,0), -- Số tầng (nhà)
  "NPA_HOUSE_AREA_BUILDING" NUMBER(20,3), -- Diện tích xây dựng
  "NPA_HOUSE_AREA_FLOOR" NUMBER(20,3), -- Diện tích sàn
  "NPA_HOUSE_AREA_HEADQUARTER_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm trụ sở làm việc
  "NPA_HOUSE_AREA_BUSINESS_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cơ sở hoạt động sự nghiệp
  "NPA_HOUSE_AREA_HOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà để ở
  "NPA_HOUSE_AREA_WAREHOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà kho
  "NPA_HOUSE_AREA_TEMPORARY_HOUSE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích làm nhà tạm
  "NPA_HOUSE_AREA_LEASE_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích cho thuê
  "NPA_HOUSE_AREA_VACANT_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bỏ trống
  "NPA_HOUSE_AREA_OCCUPIED_USAGE" NUMBER(20,3), -- Hiện trạng: Diện tích bị lấn chiếm
  "NPA_HOUSE_AREA_OTHER_USAGE" NUMBER(20,3), -- Hiện trạng:Diện tích sử dụng khác

  "NPA_VEHICLE_COUNTRY_OF_ORIGIN" VARCHAR2(500 BYTE), -- Nước sản xuất
  "NPA_VEHICLE_BRAND_NAME" VARCHAR2(500 BYTE), -- Nhãn hiệu
  "NPA_VEHICLE_VEHICLE_IDENTIFICATION_NUMBER" VARCHAR2(250 BYTE), -- Số khung/Mã nhận dạng phương tiện
  "NPA_VEHICLE_REGISTRATION_PLATE_NUMBER" VARCHAR2(250 BYTE), -- Biển kiểm soát/số hiệu kiểm soát
  "NPA_VEHICLE_SIZE" NUMBER(10,0), -- Kích cỡ (Số chỗ ngồi/kích cỡ tàu ...)
  "NPA_VEHICLE_CAPACITY" VARCHAR2(500 BYTE), -- Sức chứa (tải trọng/công suất ...)
  
  "NPA_OTHER_ASSET_SPECIFICATIONS" VARCHAR2(4000 BYTE), -- Thông số kỹ thuật
  "NPA_OTHER_ASSET_SERIAL_NUMBER" VARCHAR2(250 BYTE), -- Số serie
  "NPA_OTHER_ASSET_SUPPLIER" VARCHAR2(500 BYTE), -- Nhà cung cấp
  "NPA_OTHER_ASSET_COUNTRY_OF_ORIGIN" VARCHAR2(500 BYTE), -- Nước sản xuất
  "NPA_OTHER_ASSET_BRAND_NAME" VARCHAR2(500 BYTE), -- Nhãn hiệu
  
  
  "OTHER_INFORMATION" CLOB, -- Các thông tin khác
  "NOTES" CLOB -- Ghi chú
  
);

CREATE TABLE "ASSET_INVENTORY_REPORTS" -- Biên bản kiểm kê tài sản
(
  "ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "UNIT_ID" NUMBER(10,0) REFERENCES "UNITS"("ID") NULL, -- Đơn vị kiểm kê
  "NAME" VARCHAR2(500 BYTE) NOT NULL, -- Tên phiếu kiểm kê
  "DESCRIPTION" VARCHAR2(500 BYTE) NOT NULL, -- Mô tả phiếu kiểm kê
  "INVENTORY_FORM" NUMBER(10,0) NOT NULL, -- Hình thức kiểm kê. 1: Kiểm kê thường niên. 2: Kiểm kê đột xuất. 3: Kiểm kê dể xử lý. 4: Kiểm kê khác
  "INVENTORY_YEAR" NUMBER(10,0) NOT NULL, -- Năm kiểm kê
  "CREATED_DATE" DATE NOT NULL, -- Ngày lập biên bản
  "INVENTORY_DATE" DATE, -- Ngày kiểm kê
  "APPROVED_DATE" DATE, -- Ngày duyệt
  "APPROVER" VARCHAR2(4000 BYTE), -- Người duyệt
  "STATUS" NUMBER(10,0), -- Trạng thái biên bản. 1: Chờ duyệt. 2: Đã duyệt đang xử lý. 3: Đã xử lý xong. 4: Từ chối. 5: Đã hủy
  "SYNC_USER_ID" NUMBER(10,0) REFERENCES "SYNC_USERS"("ID") NOT NULL, -- Tài khoản đồng bộ
  "SYNC_DATE" DATE DEFAULT SYSDATE NOT NULL -- Ngày đồng bộ
);

CREATE TABLE "ASSET_INVENTORY_DETAILS" -- Tài sản kiểm kê
(
  "ID" NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "ASSET_INVENTORY_REPORT_ID" NUMBER(10,0) REFERENCES "ASSET_INVENTORY_REPORTS"("ID") NOT NULL,
  "ASSET_ID" NUMBER(18,0) REFERENCES "ASSETS"("ID") NOT NULL,
  "ASSET_NAME" VARCHAR2(4000 BYTE) NOT NULL,
  "HANDLING_RESULT" NUMBER(10,0) NOT NULL, -- Xử lý tài sản sau kiểm kê
  "NOTE" VARCHAR2(4000 BYTE) NULL,
  "SYNC_USER_ID" NUMBER(10,0) REFERENCES "SYNC_USERS"("ID") NOT NULL, -- Tài khoản đồng bộ
  "SYNC_DATE" DATE DEFAULT SYSDATE NOT NULL -- Ngày đồng bộ
);

CREATE TABLE "ASSET_DEPRECIATIONS" -- Khấu hao tài sản
(
  "ID" NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "ASSET_ID" NUMBER(18,0) REFERENCES "ASSETS"("ID") NOT NULL, -- Mã tài sản
  "YEAR" NUMBER(10,0) NOT NULL, -- Năm khấu hao
  "MONTH" NUMBER(10,0) NOT NULL, -- Tháng khấu hao
  "DEPRECIATION_VALUE" NUMBER(18,0) NOT NULL, -- Giá trị khấu hao
  "ACCUMULATED_DEPRECIATION_VALUE" NUMBER(18,0) NOT NULL, -- Giá trị khấu hao tích lũy
  "ORIGINAL_VALUE" NUMBER(18,0) NOT NULL, -- Nguyên giá
  "RESIDUAL_VALUE" NUMBER(18,0) NOT NULL, -- Giá trị còn lại
  "SYNC_USER_ID" NUMBER(10,0) REFERENCES "SYNC_USERS"("ID") NOT NULL, -- Tài khoản đồng bộ
  "SYNC_DATE" DATE DEFAULT SYSDATE NOT NULL -- Ngày đồng bộ
  -- OTHER INFO
);

CREATE TABLE "ASSET_AMORTIZATIONS" -- Hao mòn tài sản
(
  "ID" NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "ASSET_ID" NUMBER(18,0) REFERENCES "ASSETS"("ID") NOT NULL, -- Mã tài sản
  "YEAR" NUMBER(10,0) NOT NULL, -- Năm hao mòn
  "AMORTIZATION_VALUE" NUMBER(18,0) NOT NULL, -- Giá trị hao mòn
  "ACCUMULATED_AMORTIZATION_VALUE" NUMBER(18,0) NOT NULL, -- Giá trị hao mòn tích lũy
  "ORIGINAL_VALUE" NUMBER(18,0) NOT NULL, -- Nguyên giá
  "RESIDUAL_VALUE" NUMBER(18,0) NOT NULL, -- Giá trị còn lại
  "SYNC_USER_ID" NUMBER(10,0) REFERENCES "SYNC_USERS"("ID") NOT NULL, -- Tài khoản đồng bộ
  "SYNC_DATE" DATE DEFAULT SYSDATE NOT NULL -- Ngày đồng bộ
  -- OTHER INFO
);

CREATE TABLE "ASSET_EXPLOITATIONS" -- Khai thác tài sản
(
  "ID" NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "ASSET_ID" NUMBER(18,0) REFERENCES "ASSETS"("ID") NOT NULL, -- Mã tài sản
  "UNIT_ID" NUMBER(10,0) REFERENCES "UNITS"("ID") NULL, -- Đơn vị sở hữu tài sản
  "EXPLOITATION_TYPE" NUMBER(10,0) NOT NULL, -- Hình thức khai thác. 1: Cho thuê. 2: Tham gia kinh doanh. 3: Mang liên doanh, liên kết
  "START_DATE" NUMBER(10,0) NOT NULL, -- Ngày bắt đầu khai thác
  "END_DATE" NUMBER(10,0) NOT NULL, -- Ngày kết thúc khai thác
  "DECISION_CODE" VARCHAR2(50 BYTE) NOT NULL, -- Số quyết định
  "ISSUED_DATE" DATE NOT NULL, -- Ngày quyết định
  "APPROVER" VARCHAR2(250 BYTE) NOT NULL, -- Người quyết định
  "PRICE" NUMBER(18,0) NOT NULL, -- Đơn giá
  "EXPLOITED_TIME" NUMBER(10,0) NOT NULL, -- Thời gian khai thác
  "EXPLOITED_VALUE" NUMBER(18,0) NOT NULL, -- Số tiền thu được
  "CONTRACT" VARCHAR2(4000 BYTE) NULL, -- Hợp đồng liên quan
  "PARTNER" VARCHAR2(4000 BYTE) NULL, -- Đối tác/Đơn vị thuê
  "NOTES" CLOB NULL, -- Ghi chú
  "SYNC_USER_ID" NUMBER(10,0) REFERENCES "SYNC_USERS"("ID") NOT NULL, -- Tài khoản đồng bộ
  "SYNC_DATE" DATE DEFAULT SYSDATE NOT NULL -- Ngày đồng bộ
);




